title: 'Ayushman Devraj Homepage'
description: "A Personal Homepage"
baseurl: "/jekyll-theme-console"
url: "https://b2a3e8.github.io"
#google_analytics: UA-NNNNNNNN-N

header_pages:
  - Home.md
  - Blog Posts.md
  - About.md
  - Contact.md

style: dark

footer: 'Follow me on <a href="https://twitter.com/ayushmandevraj">twitter</a>'




theme: jekyll-theme-console

plugins:
  - jekyll-seo-tag
