title: 'Ayushman Devraj Test Site'
description: "site description for seo"
baseurl: "/jekyll-theme-console"
url: "https://b2a3e8.github.io"

header_pages:
  - Home.md
  - Blog Posts.md
  - About.md
  - Contact.md

style: dark

footer: 'follow me on <a href="https://twitter.com/ayushmandevraj">twitter</a>'


remote_theme: b2a3e8/jekyll-theme-console
theme: jekyll-theme-console
